name: GoReleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to release (e.g., v1.2.3)'
        required: true
        default: 'v0.0.0'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.24.0'
          cache: true

      - name: Generate Build Metadata
        run: |
          # 自动触发时使用 git describe 获取版本
          # 手动触发时使用输入的 tag
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            echo "VERSION=${{ inputs.tag }}" >> $GITHUB_ENV
          else
            echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV
          fi
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --release ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
          COMMIT: ${{ env.COMMIT }}
          BUILD_DATE: ${{ env.BUILD_DATE }}
